[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd server && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "momentumx-server"
source = "."

[services.variables]
NODE_ENV = "production"
